export const Topic=[
    {
        key:1,
        head:"General",
        faq:[
            {
                question:"Do I need a licence to install a solar energy system in Singapore?",
                answer:"If you’re planning to install solar panels for residential use in Singapore with a capacity of less than 1MWac, you don’t need to obtain a license. However, for non-residential solar installations and all solar panel installations that are 1MWac and above, it may be necessary to apply for both the Electrical Installation and Electricity Generation Licenses. An Electrical Installation (EI) License will be required if the load demand of a non-residential electrical installation, including a solar panel system, exceeds 45kVA. In this case, a Licensed Electrical Worker (LEW) will need to be appointed to handle the electrical installation and assist with the license application. Additionally, an Electricity Generation License will be necessary for any solar panel system with an aggregate inverter capacity exceeding 1MWac at the point where it connects to SP Group’s substation.",
            },
            {
                question:"How does solar generate savings?",
                answer:"Solar energy generates savings by reducing or offsetting a business's or homeowner's electricity bills. When solar panels are installed on a property, they generate electricity from sunlight, which can be used to power appliances and equipment within the property. This means that the property owner will need to purchase less electricity from the grid, resulting in lower electricity bills. In addition to reducing electricity bills, solar energy can also generate savings through the various incentives and programmes offered by governments and utilities to encourage the adoption of solar energy. In Singapore, businesses and homeowners who install solar PV systems can enjoy enhanced capital allowances and net metering, which allows excess solar energy to be sold back to the grid for credits. Moreover, solar energy can also help businesses and homeowners hedge against future electricity price increases, which can result in significant savings over the long term. With solar energy, businesses and homeowners can lock in their electricity costs at a fixed rate and reduce their exposure to volatile electricity prices. In Singapore, the advantages of solar energy systems outweigh the initial investment amount. What’s more, even if a solar energy system is financed, it still pays for itself and generates more money every month in savings than the money which is paid back for the financing. The net result being positive, solar energy systems have become a “no-brainer” for all as essentially they are free if you consider the immediate savings. Take a first step towards understanding how it all works – contact us now !",
            },
            {
                question:"Does solar work in rainy weather?",
                answer:"Solar panels can still generate electricity during rainy weather, although their efficiency will be reduced. This is because solar panels rely on sunlight to generate electricity, and rainy weather typically means less sunlight is available. Modern solar panels are designed to be relatively efficient even in low-light conditions, so they can still generate some electricity even on cloudy or rainy days. In fact, some types of solar panels are specifically designed to perform better in low-light conditions.It’s also worth noting that solar panels don’t need direct sunlight to work - they can still generate electricity on overcast days or in shaded areas, although again, their efficiency will be lower.Overall, while rainy weather can affect the amount of electricity generated by solar panels, they can still be a valuable source of renewable energy even in less-than-ideal conditions. In South-East Asia and Singapore for example, there will be a seasonal variation in the production of solar panels which we can see throughout the months. The drop in solar energy production during rainy months would be circa 30-40% as compared to hot months. Modern solar design software can predict seasonal energy production with 80-90% accuracy. The more precise the design, the more exact will be your savings’ prediction! Our expert team at SG Solar Home can help you with an optimal solar system design for your home or business. Contact us to learn more.",
            },
            {
                question:"How long is the warranty on solar PV systems?",
                answer:"The warranty on solar PV systems can vary depending on the manufacturer and the type of panel used. Typically, solar panel manufacturers offer a product warranty of 10 to 25 years, which covers defects and issues that arise due to manufacturing or material defects. In addition to the product warranty, solar PV system installers may offer workmanship warranties, which cover the installation and wiring of the system. Workmanship warranties typically range from 1 to 5 years. It’s worth noting that solar panels can continue to generate electricity beyond their warranty period, but the efficiency of the panels may gradually decrease over time. Most solar panels have a degradation rate of 0.5% to 1% per year, which means that the panels will still be able to generate electricity at a reduced rate even after the warranty period has ended. When selecting a solar PV system, it’s important to consider the warranty and reliability of the manufacturer and installer. Choosing reputable and established manufacturers and installers can help ensure that the system will perform as expected and provide long-term value.",
            },
            {
                question:"Is solar panel production good in Singapore?",
                answer:"Although Singapore is a small island nation with limited land availability, it still has good potential for solar installation due to its location near the equator, which means that it receives a high amount of solar irradiance throughout the year. The country has also been actively promoting the use of solar energy in recent years to reduce its reliance on fossil fuels and achieve its climate goals. Despite its relatively small land area, Singapore has set a target to deploy 2 GWp of solar PV systems on public sector buildings by 2030. In addition, there have been various policies and initiatives to support the adoption of solar energy, such as net metering, SolarNova programme on public sector buildings and HDBs and enhanced capital allowances for businesses. Moreover, with the continued advancement of solar technology, the efficiency and cost-effectiveness of solar PV systems are improving, making them an increasingly viable option for businesses and homeowners in Singapore.",
            },
            {
                question:"What is the lifespan of solar panels?",
                answer:"Most manufacturers provide a warranty on solar panels for 25 years or more. Solar panels can last much longer than their warranty period if they are well-maintained and not damaged by external factors such as severe weather conditions. In fact, some solar panels can continue to produce electricity for 30 years or more. It’s worth noting that the solar panel efficiency may decrease slightly over time, but this is a gradual process and the panels can still be very effective in generating solar energy.",
            },
            {
                question:"EV charging installation in Singapore",
                answer:"If you live in a landed house in Singapore and want to install an EV charger, you should engage a Licensed Electrical Worker (LEW) who is also an LTA-approved EV charger installer to install, test, and certify the fitness of the EV Charging System (EVCS) installation before it is put into service. Contact an LTA-approved EVCS installer to conduct a site assessment and provide a quotation for the installation. The installer will do the following: Apply for an Electrical Works Permit from the Energy Market Authority (EMA) for the installation of the charger. Engage a licensed electrician to install the EV charger. Once the installation is completed, endorse the installation and submit the necessary documents to EMA for approval. After EMA approval, connect the charger to the electrical solar energy supply. Note that the cost of the installation will depend on factors such as the charger type, the location of the charger, and the existing electrical infrastructure at your property. A typical installation will range from $1500 to $3,500, including installation, commissioning, mandatory inspection by LEW and 12-months’ installation and component warranty. You should also look at powering your EV charger with a solar energy installation as it provides the most cost-efficient way to do so.",
            },

        ]
        
    },
    {
        key:2,
        head:"Installation",
        faq:[
            {
                question:"How long does it take for a solar PV installation to be completed?",
                answer:"The overall installation process for a residential solar panel system can take 1-2 weeks. It would of course be longer for a commercial system, depending on its size.",
            },
            {
                question:"Who do I reach out to install a solar PV system on my building?",
                answer:"Here are several options available for finding an installation partner to install a solar panel system on your building:Online directories: You can search online directories such as the Singapore Solar Directory or the Green Mark Directory to find certified solar PV system installers in Singapore.Referrals: You can ask for referrals from friends, colleagues, or other building owners who have already installed a solar PV system.Industry associations: You can reach out to industry associations such as the Sustainable Energy Association of Singapore or the Solar Energy Research Institute of Singapore for recommendations.Solar PV system manufacturers: You can also contact solar PV system manufacturers to ask for recommendations on certified installers who are authorized to install their products.Once you have a list of potential installation partners for your solar panel system, it is important to evaluate them based on their experience, expertise, accreditation, and customer service before making a final decision. On Sunollo, we do this work for you and you will get quotes from each installer to compare pricing for solar panel costs and warranties, in one place. Start your solar project and comparing quotes online now!",
            },
        ]
    },


    {
        key:3,
        head:"Cost & Financing",
        faq:[
            {
                question:"How much do solar panels cost to install, if I invest into it?",
                answer:"The cost of installing solar panels on a building in Singapore can vary depending on several factors, such as the size of the system, the type of panels used, and the complexity of the installation. However, as of 2023, the typical cost for a solar power system in Singapore ranges from SGD 1 to nearly SGD 2 per watt-peak (Wp) installed.Smaller solar energy systems are comparatively more expensive than larger systems. For example, a 10 kWp residential rooftop solar panel system can cost around S$1,540/kWp while a 1,000 kWp industrial rooftop PV system can cost around S$940/kWp. Operation and Maintenance (O&M) costs range between 1 to 1.45% of upfront costs (1% for large rooftop solar panel systems compared to 1.45% for smaller systems).To give you an idea of the cost, a 100 kWp commercial solar power system would cost approximately SGD 100,000 to SGD 140,000. However, it’s important to note that this is just a rough estimate, and the actual cost can vary based on several factors. ]It’s also worth mentioning that there are incentives available that can help households and businesses offset the upfront costs of installing solar panel systems in Singapore, such as enhanced capital allowances for businesses, net metering and the sale of Renewable Energy Certificates (RECs). These incentives can help make solar energy more financially viable for businesses and households and reduce the payback period of the investment.Sunollo provides a platform for customers to get the best commercial rates on solar panel installations, with quotes given by pre-selected qualified installers. We don’t charge any commission on our customers. Try it now and get the best rates for your solar panel system!",
            },
            {
                question:"Are there any incentives for going solar in Singapore for households and businesses?",
                answer:"The cost of solar panel installations has significantly reduced in recent years due to the progressive reduction in solar technology costs. While there are no direct grants for installing solar panels in Singapore, the government has introduced net metering, which allows additional revenue generation from the energy produced as it’s exported to the grid. This is an attractive incentive for both households and businesses to invest in solar power.Another incentive for installing solar panels is the booming market for Renewable Energy Certificates (or RECs). RECs are valued at nearly SGD 40/REC or per 1 MWh of energy produced by the solar energy system. This means that households and businesses can earn additional revenue by selling the RECs they earn from their solar panel installations. Moreover, businesses in Singapore can benefit from enhanced capital allowances that help in offsetting the upfront costs of installing solar PV systems. These incentives can help make solar more financially viable for both businesses and households and reduce the payback period of the investment.At Sunollo, our team can advise you on solar PV system incentives and how to maximize them in order to reduce your pay-back time. By installing solar panels, you can save on your electricity bills, reduce your carbon footprint, and earn additional revenue. Contact us today to get expert advice or try our platform free of charge to get competing quotes for your solar project.",
            },
            {
                question:"How much money can solar energy save?",
                answer:"Solar panel systems in Singapore can save homeowners around 30% to 50% on their monthly electricity bills, taking into account that the unused electricity will be fed into the grid.",
            },
            {
                question:"How long is the warranty on solar PV systems?",
                answer:"The warranty on solar PV systems can vary depending on the manufacturer and the type of panel used. Typically, solar panel manufacturers offer a product warranty of 10 to 25 years, which covers defects and issues that arise due to manufacturing or material defects. In addition to the product warranty, solar PV system installers may offer workmanship warranties, which cover the installation and wiring of the system. Workmanship warranties typically range from 1 to 5 years. It’s worth noting that solar panels can continue to generate electricity beyond their warranty period, but the efficiency of the panels may gradually decrease over time. Most solar panels have a degradation rate of 0.5% to 1% per year, which means that the panels will still be able to generate electricity at a reduced rate even after the warranty period has ended. When selecting a solar PV system, it’s important to consider the warranty and reliability of the manufacturer and installer. Choosing reputable and established manufacturers and installers can help ensure that the system will perform as expected and provide long-term value.",
            },
            {
                question:"Is solar panel production good in Singapore?",
                answer:"Although Singapore is a small island nation with limited land availability, it still has good potential for solar installation due to its location near the equator, which means that it receives a high amount of solar irradiance throughout the year. The country has also been actively promoting the use of solar energy in recent years to reduce its reliance on fossil fuels and achieve its climate goals. Despite its relatively small land area, Singapore has set a target to deploy 2 GWp of solar PV systems on public sector buildings by 2030. In addition, there have been various policies and initiatives to support the adoption of solar energy, such as net metering, SolarNova programme on public sector buildings and HDBs and enhanced capital allowances for businesses. Moreover, with the continued advancement of solar technology, the efficiency and cost-effectiveness of solar PV systems are improving, making them an increasingly viable option for businesses and homeowners in Singapore.",
            },
            {
                question:"What is the lifespan of solar panels?",
                answer:"Most manufacturers provide a warranty on solar panels for 25 years or more. Solar panels can last much longer than their warranty period if they are well-maintained and not damaged by external factors such as severe weather conditions. In fact, some solar panels can continue to produce electricity for 30 years or more. It’s worth noting that the solar panel efficiency may decrease slightly over time, but this is a gradual process and the panels can still be very effective in generating solar energy.",
            },
            {
                question:"EV charging installation in Singapore",
                answer:"If you live in a landed house in Singapore and want to install an EV charger, you should engage a Licensed Electrical Worker (LEW) who is also an LTA-approved EV charger installer to install, test, and certify the fitness of the EV Charging System (EVCS) installation before it is put into service. Contact an LTA-approved EVCS installer to conduct a site assessment and provide a quotation for the installation. The installer will do the following: Apply for an Electrical Works Permit from the Energy Market Authority (EMA) for the installation of the charger. Engage a licensed electrician to install the EV charger. Once the installation is completed, endorse the installation and submit the necessary documents to EMA for approval. After EMA approval, connect the charger to the electrical solar energy supply. Note that the cost of the installation will depend on factors such as the charger type, the location of the charger, and the existing electrical infrastructure at your property. A typical installation will range from $1500 to $3,500, including installation, commissioning, mandatory inspection by LEW and 12-months’ installation and component warranty. You should also look at powering your EV charger with a solar energy installation as it provides the most cost-efficient way to do so.",
            },

        ]
        
    },
]

export const Leftcol=[
    {
        topic:"General",
    },
    {
        topic:"Installer",
    },
    {
        topic:"Cost & Financing",
    },
    {
        topic:"Maintenance",
    },
    {
        topic:"Referral",
    },
    {
        topic:"Renewable Energy Certificates",
    },
]